language: "node_js"
services:
  - redis-server
node_js:
  - '0.10'
  - '0.11'
script: NODE_ENV=test node node_modules/.bin/istanbul cover ./node_modules/.bin/_mocha --report lcovonly -- -u exports test --bail
after_script: "npm install coveralls@2.10.0 && cat ./coverage/lcov.info | coveralls"
